import 'package:flutter/material.dart';

void main() => runApp(const SourcerApp());

class SourcerApp extends StatelessWidget {
  const SourcerApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sourcer – Wholesale Assistant',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        colorSchemeSeed: Colors.deepPurple,
        inputDecorationTheme: const InputDecorationTheme(
          border: OutlineInputBorder(),
        ),
      ),
      home: const SourcerHome(),
    );
  }
}

class SourcerHome extends StatefulWidget {
  const SourcerHome({super.key});
  @override
  State<SourcerHome> createState() => _SourcerHomeState();
}

class _SourcerHomeState extends State<SourcerHome> {
  // Inputs
  final urlCtrl = TextEditingController();
  final addrCtrl = TextEditingController();
  final zipCtrl  = TextEditingController(text: '77033'); // Houston example
  final arvCtrl  = TextEditingController(text: '250000');
  final feeCtrl  = TextEditingController(text: '5000');

  double factor = 0.65;              // MAO factor (0.55–0.75)
  double risk   = 0.50;              // 0 (safe) .. 1 (aggressive)
  bool showDisclaimers = true;

  // Simple ZIP → rate profile (placeholder "standard pricing tables")
  // Costs are rough per-unit anchors and will be tuned by zip region.
  final Map<String, ZipRate> zipRates = {
    '770': ZipRate(multiplier: 0.9, domDays: 35, discountTrend: -0.02, label: 'Houston area'),
    '900': ZipRate(multiplier: 1.25, domDays: 42, discountTrend: -0.03, label: 'Los Angeles area'),
    'default': ZipRate(multiplier: 1.0, domDays: 30, discountTrend: -0.01, label: 'National'),
  };

  // Line items (can be edited later; for now generated by ZIP profile)
  late List<RepairItem> items;

  @override
  void initState() {
    super.initState();
    items = _generateRepairsForZip(zipCtrl.text);
    zipCtrl.addListener(() {
      setState(() => items = _generateRepairsForZip(zipCtrl.text));
    });
  }

  ZipRate _rateForZip(String z) {
    if (z.length >= 3) {
      final key = z.substring(0, 3);
      if (zipRates.containsKey(key)) return zipRates[key]!;
    }
    return zipRates['default']!;
  }

  List<RepairItem> _generateRepairsForZip(String z) {
    final r = _rateForZip(z).multiplier;
    // baseline costs
    final base = <RepairItem>[
      RepairItem('Interior paint', '1000 sqft', 1, 1.80),
      RepairItem('Flooring (LVP)', '1000 sqft', 1, 3.20),
      RepairItem('Kitchen refresh', 'cabinets/ctops', 1, 6500),
      RepairItem('Bathroom (x2) refresh', 'vanity/tile', 1, 4500),
      RepairItem('Roof patch/allowance', 'per job', 1, 2500),
      RepairItem('Windows (allowance)', 'per job', 1, 1800),
      RepairItem('HVAC service', 'per job', 1, 600),
      RepairItem('Electrical/Plumbing misc', 'allowance', 1, 1500),
      RepairItem('Trash/demo/cleanup', 'per job', 1, 1200),
      RepairItem('Contingency', '10%', 1, 2000),
    ];
    return base
        .map((e) => e.copyWith(unitCost: (e.unitCost * r)))
        .toList();
  }

  double _toDouble(String s) => double.tryParse(s.replaceAll(',', '').trim()) ?? 0.0;

  @override
  Widget build(BuildContext context) {
    final rates = _rateForZip(zipCtrl.text);
    final arv = _toDouble(arvCtrl.text);
    final repairs = items.fold<double>(0, (sum, e) => sum + e.total);
    final fee = _toDouble(feeCtrl.text);

    // Offer band logic
    final target = _mao(arv, factor, repairs, fee);
    final aggressive = _mao(arv, (factor - 0.03).clamp(0.55, 0.75), repairs, fee);
    final safe = _mao(arv, (factor + 0.03).clamp(0.55, 0.75), repairs, fee);

    // Risk nudges the recommended pick between aggressive/safe
    final recommended = _lerp(safe, aggressive, risk);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Sourcer – New Deal'),
        actions: [
          IconButton(
            tooltip: 'Reset',
            onPressed: () => setState(() {
              urlCtrl.clear();
              addrCtrl.clear();
              zipCtrl.text = '77033';
              arvCtrl.text = '250000';
              feeCtrl.text = '5000';
              factor = 0.65; risk = 0.50;
              items = _generateRepairsForZip(zipCtrl.text);
            }),
            icon: const Icon(Icons.refresh),
          ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          _section('Deal input', [
            TextField(controller: urlCtrl, decoration: const InputDecoration(labelText: 'Listing URL (Zillow/Redfin/etc)')),
            const SizedBox(height: 12),
            TextField(controller: addrCtrl, decoration: const InputDecoration(labelText: 'Address (optional)')),
            const SizedBox(height: 12),
            Row(children: [
              Expanded(child: TextField(
                controller: zipCtrl,
                keyboardType: TextInputType.number,
                decoration: const InputDecoration(labelText: 'ZIP *'),
              )),
              const SizedBox(width: 12),
              Expanded(child: TextField(
                controller: arvCtrl,
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                decoration: const InputDecoration(labelText: 'ARV (\$) *'),
                onChanged: (_) => setState((){}),
              )),
            ]),
            const SizedBox(height: 12),
            Row(children: [
              Expanded(child: TextField(
                controller: feeCtrl,
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                decoration: const InputDecoration(labelText: 'Assignment fee (\$)'),
                onChanged: (_) => setState((){}),
              )),
              const SizedBox(width: 12),
              Expanded(child: _factorSlider()),
            ]),
            const SizedBox(height: 8),
            _riskSlider(),
            const SizedBox(height: 8),
            Text(
              'Market signals: ${rates.label} • DOM ~${rates.domDays} days • price trend ${(rates.discountTrend*100).toStringAsFixed(1)}%/mo',
              style: TextStyle(color: Theme.of(context).colorScheme.secondary),
            ),
          ]),

          const SizedBox(height: 16),
          _section('Repair budget (auto-estimated)', [
            ...items.map((e) => _repairRow(e)),
            const Divider(),
            _kv('Repairs total', _money(repairs), big: true),
            const SizedBox(height: 8),
            Wrap(
              spacing: 8,
              children: [
                OutlinedButton.icon(
                  onPressed: () => setState(() => items = _generateRepairsForZip(zipCtrl.text)),
                  icon: const Icon(Icons.auto_fix_high), label: const Text('Re-estimate by ZIP'),
                ),
                OutlinedButton.icon(
                  onPressed: () => setState(() => items.add(RepairItem('Custom item', 'each', 1, 1000))),
                  icon: const Icon(Icons.add), label: const Text('Add line item'),
                ),
              ],
            ),
          ]),

          const SizedBox(height: 16),
          _section('Offer range (MAO = ARV × Factor − Repairs − Fee)', [
            _offerCard('Aggressive', aggressive, Colors.red),
            _offerCard('Target', target, Colors.orange),
            _offerCard('Safe', safe, Colors.green),
            const SizedBox(height: 6),
            _kv('Recommended (by risk slider)', _money(recommended), big: true),
          ]),

          const SizedBox(height: 16),
          _section('Negotiation scripts', [
            ..._scripts(arv, repairs, fee, recommended).map((s) => Padding(
              padding: const EdgeInsets.only(bottom: 8),
              child: SelectableText('• $s'),
            )),
          ]),

          const SizedBox(height: 16),
          Row(children: [
            Expanded(child: FilledButton.icon(
              onPressed: () => _snack(context, 'Saved locally (stub). Next: connect to Supabase/CRM.'),
              icon: const Icon(Icons.save), label: const Text('Save to Pipeline'),
            )),
            const SizedBox(width: 12),
            Expanded(child: OutlinedButton.icon(
              onPressed: () => _snack(context, 'PDF export stub. I can wire printing next.'),
              icon: const Icon(Icons.picture_as_pdf), label: const Text('PDF / Share'),
            )),
          ]),

          if (showDisclaimers) ...[
            const SizedBox(height: 24),
            Text(
              'Disclaimer: All values are estimates for investor due diligence only. '
              'ARV, comps, and repair budgets should be verified by licensed professionals. '
              'Market data and pricing multipliers are placeholders.',
              style: Theme.of(context).textTheme.bodySmall,
            ),
          ],
          const SizedBox(height: 24),
        ],
      ),
    );
  }

  // ---- UI helpers

  Widget _section(String title, List<Widget> children) => Card(
        elevation: 0,
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text(title, style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w700)),
            const SizedBox(height: 12),
            ...children,
          ]),
        ),
      );

  Widget _kv(String k, String v, {bool big = false}) => Row(
        children: [
          Expanded(child: Text(k, style: TextStyle(fontWeight: big ? FontWeight.w700 : FontWeight.w600, fontSize: big ? 16 : 14))),
          Text(v, style: TextStyle(fontWeight: big ? FontWeight.w800 : FontWeight.w600, fontSize: big ? 18 : 14)),
        ],
      );

  Widget _factorSlider() => Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Factor (0.55–0.75)'),
          Slider(
            value: factor,
            onChanged: (v) => setState(() => factor = v),
            min: 0.55,
            max: 0.75,
            divisions: 20,
            label: factor.toStringAsFixed(2),
          ),
        ],
      );

  Widget _riskSlider() => Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Risk preference'),
          Slider(
            value: risk,
            onChanged: (v) => setState(() => risk = v),
            min: 0.0, max: 1.0, divisions: 10,
            label: risk <= .33 ? 'Safe' : (risk >= .67 ? 'Aggressive' : 'Balanced'),
          ),
        ],
      );

  Widget _offerCard(String label, double amount, Color color) {
    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(12),
        // ignore: deprecated_member_use
        border: Border.all(color: color.withOpacity(.35)),
        // ignore: deprecated_member_use
        color: color.withOpacity(.06),
      ),
      child: _kv(label, _money(amount), big: true),
    );
  }

  Widget _repairRow(RepairItem e) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(children: [
        Expanded(
          flex: 2,
          child: TextFormField(
            initialValue: e.name,
            decoration: const InputDecoration(labelText: 'Item'),
            onChanged: (v) => setState(() => e.name = v),
          ),
        ),
        const SizedBox(width: 8),
        Expanded(
          child: TextFormField(
            initialValue: e.qty.toStringAsFixed(0),
            keyboardType: TextInputType.number,
            decoration: const InputDecoration(labelText: 'Qty'),
            onChanged: (v) => setState(() => e.qty = double.tryParse(v) ?? e.qty),
          ),
        ),
        const SizedBox(width: 8),
        Expanded(
          child: TextFormField(
            initialValue: e.unitCost.toStringAsFixed(0),
            keyboardType: const TextInputType.numberWithOptions(decimal: true),
            decoration: const InputDecoration(labelText: 'Unit \$'),
            onChanged: (v) => setState(() => e.unitCost = double.tryParse(v) ?? e.unitCost),
          ),
        ),
        const SizedBox(width: 8),
        SizedBox(
          width: 110,
          child: Text(_money(e.total), textAlign: TextAlign.end),
        ),
        IconButton(
          icon: const Icon(Icons.delete_outline),
          onPressed: () => setState(() => items.remove(e)),
          tooltip: 'Remove',
        ),
      ]),
    );
  }

  // ---- Logic helpers

  double _mao(double arv, double f, double repairs, double fee) {
    return (arv * f) - repairs - fee;
  }

  double _lerp(double a, double b, double t) => a + (b - a) * t;

  String _money(double v) {
    final s = v.isNaN || v.isInfinite ? 0.0 : v;
    return '\$${s.toStringAsFixed(0)}';
  }

  List<String> _scripts(double arv, double repairs, double fee, double offer) {
    final lines = <String>[
      "We're cash, quick close, no repairs. Given the comps and work needed (~${_money(repairs)}), our number is ${_money(offer)}.",
      "Investor pricing uses MAO = ARV × Factor − Repairs − Fee. With ARV ~${_money(arv)} and the current market, we're at ${_money(offer)}.",
      "I can be flexible on close date and fees. If we handle all closing costs, would ${_money(offer)} work today?",
      "If we take out the roof/HVAC allowance, I can stretch a bit. Where do we need to be to lock this up?",
    ];
    return lines;
  }

  void _snack(BuildContext ctx, String msg) {
    ScaffoldMessenger.of(ctx).showSnackBar(SnackBar(content: Text(msg)));
  }
}

// ---- Models

class ZipRate {
  final double multiplier;    // >1.0 = pricier labor/materials
  final int domDays;          // days on market (placeholder)
  final double discountTrend; // monthly price change (%)
  final String label;
  ZipRate({required this.multiplier, required this.domDays, required this.discountTrend, required this.label});
}

class RepairItem {
  String name;
  String note;
  double qty;
  double unitCost;
  RepairItem(this.name, this.note, this.qty, this.unitCost);

  double get total => qty * unitCost;

  RepairItem copyWith({String? name, String? note, double? qty, double? unitCost}) =>
      RepairItem(name ?? this.name, note ?? this.note, qty ?? this.qty, unitCost ?? this.unitCost);
}
